install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y cabal
  - choco install -y ghc --version 8.0.2
  - refreshenv
  # See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491
  # NB: Do this after refreshenv, otherwise it will be clobbered!
  - set PATH=%APPDATA%\cabal\bin;C:\msys64\usr\bin;C:\Program Files\Git\mingw64\bin;%PATH%
  - pacman -Sy --noconfirm mingw-w64-x86_64-pkg-config
  - cabal --version
  - cabal update
  - cabal install happy alex

cache:
  - dist-newstyle

build_script:
  - cabal new-configure --enable-tests
  - appveyor-retry cabal new-build lib:Cabal --only-dependencies
  - cabal new-build lib:Cabal
  - appveyor-retry cabal new-build Cabal:tests --only-dependencies
  - cabal new-test Cabal
  - appveyor-retry cabal new-build exe:cabal exe:cabal-tests --only-dependencies
  - cabal new-build exe:cabal
  - cabal new-run cabal-tests -- -j3 --with-cabal=dist-newstyle\build\x86_64-windows\ghc-8.0.2\cabal-install-2.3.0.0\build\cabal\cabal.exe
  - appveyor-retry cabal new-build cabal-install:tests --only-dependencies
  # Hack to get #5351 unblocked: these are all of c-i's tests except for unit-tests, which are apparently hanging.
  - cabal new-test cabal-install:memory-usage-tests cabal-install:solver-quickcheck cabal-install:integration-tests2
